#!/usr/bin/env sh

# This script is executed when sxmo_batterymonitor detects a battery capacity below the set threshold
# You can use it to shutdown, play a notification sound, send a message, etc

sudo busybox poweroff
