#!/bin/sh

# include common definitions
# shellcheck source=scripts/core/sxmo_common.sh
. "$(which sxmo_common.sh)"

# This hook goal is to return a non zero exit code if the device
# must be considered not idle (ongoing call, playing mpd, etc)

ongoing_call() {
	pgrep -f sxmo_modemcall.sh > /dev/null && exit 1
}

proximity_lock_on() {
	pgrep -f sxmo_proximitylock.sh > /dev/null && exit 1
}

playing_mpc() {
	command -v mpc > /dev/null || return # no mpc installed

	(mpc status | grep -q '\[playing\]') && exit 1
}

active_ssh() {
	(netstat | grep ESTABLISHED | grep -q ssh) && exit 1
}

waiting_rtcwake() {
	if grep -q crust "$LASTSTATE" && \
		grep -q rtc "$UNSUSPENDREASONFILE"; then
			exit 1
	fi
}

ongoing_call
proximity_lock_on
playing_mpc
active_ssh
waiting_rtcwake

exit 0
