#!/bin/sh

# This hook is called when the system reaches a locked state

sxmo_daemons.sh start idle_locker sxmo_idle.sh -w \
	timeout 8 'sxmo_daemons.sh start periodic_deeper sxmo_run_periodically.sh 8 sxmo_screenlock_deeper.sh --idle' \
	resume 'sxmo_daemons.sh stop periodic_deeper'
