#!/bin/sh

# include common definitions
# shellcheck source=scripts/core/sxmo_common.sh
. "$(which sxmo_common.sh)"

# This hook is called when the system reaches a locked state
sxmo_led.sh blink blue &
LEDPID=$!

sxmo_wm.sh dpms off
[ -z "$SXMO_TOUCHSCREEN_ID" ] || sxmo_wm.sh inputevent touchscreen off
[ -z "$SXMO_STYLUS_ID" ] || sxmo_wm.sh inputevent stylus off
if [ -n "$SXMO_STYLUS_ID" ] || [ -n "$SXMO_TOUCHSCREEN_ID" ]; then
	sxmo_daemons.sh stop lisgd
fi

sxmo_hooks.sh statusbar state_change
sxmo_hooks.sh statusbar locked

wait "$LEDPID"

# Start a periodic daemon (8s) "try to go to off" after 8 seconds
# Resume tasks stop daemons
sxmo_daemons.sh start idle_locker sxmo_idle.sh -w \
	timeout 8 'MUTEX_NAME=is_idle sxmo_daemons.sh start going_deeper sh -c "sxmo_hooks.sh check_state_mutexes && exec sxmo_mutex.sh holdexec sxmo_screenlock.sh off"' \
	resume 'sxmo_daemons.sh stop going_deeper' \
	timeout 12 'sxmo_daemons.sh start periodic_state_mutex_check sxmo_run_periodically.sh 10 sxmo_hooks.sh check_state_mutexes' \
	resume 'sxmo_daemons.sh stop periodic_state_mutex_check'

sxmo_daemons.sh signal desktop_widget -12
