#!/usr/bin/env sh

# This script is executed (asynchronously) when you missed a call
# You can use it to play a ring tone

# The following parameters are provided:
# $1 = Contact Name or Number (if not in contacts)

# kill existing ring playback
MPVID="$(cat "$XDG_RUNTIME_DIR/sxmo.ring.pid")"
kill $MPVID
rm "$XDG_RUNTIME_DIR/sxmo.ring.pid"
