#!/bin/sh

UNSUSPENDREASON="$1"

#The UNSUSPENDREASON can be "usb power", "modem", "rtc" (real-time clock
#periodic wakeup) or "button". You will likely want to check against this and
#decide what to do

pkill -USR2 conky # refresh conky
sxmo_statusbarupdate.sh

# Add here whatever you want to do
