#!/bin/sh

UNSUSPENDREASON="$1"

#The UNSUSPENDREASON can be "usb power", "modem", "rtc" (real-time clock
#periodic wakeup) or "button". You will likely want to check against this and
#decide what to do

if [ "$UNSUSPENDREASON" != "modem" ]; then
	NETWORKRTCSCAN="/sys/module/8723cs/parameters/rtw_scan_interval_thr"
	echo 1200 > "$NETWORKRTCSCAN"
fi

sxmo_hooks.sh statusbar time

# Add here whatever you want to do
