#!/bin/sh
# configversion: 1

# This script is called prior to suspending

# include common definitions
# shellcheck source=scripts/core/sxmo_common.sh
. "$(which sxmo_common.sh)"

pkill clickclack
sxmo_keyboard.sh close
pkill mpv #if any audio/video is playing, kill it (it might stutter otherwise)

case "$SXMO_WM" in
	dwm)
		sxmo_dmenu.sh close
		;;
esac
