#!/bin/sh

# This script is called prior to suspending

# include common definitions
# shellcheck source=scripts/core/sxmo_common.sh
. "$(which sxmo_common.sh)"

pkill clickclack
pkill -f "$KEYBOARD"
pkill mpv #if any audio/video is playing, kill it (it might stutter otherwise)
