#!/bin/sh

# include common definitions
# shellcheck source=scripts/core/sxmo_common.sh
. "$(which sxmo_common.sh)"

# This hook is called when the system reaches a off state (screen off)

sxmo_led.sh blink blue red &
LEDPID=$!

sxmo_wm.sh dpms on
[ -z "$SXMO_TOUCHSCREEN_ID" ] || sxmo_wm.sh inputevent touchscreen off
[ -z "$SXMO_STYLUS_ID" ] || sxmo_wm.sh inputevent stylus off
if [ -n "$SXMO_TOUCHSCREEN_ID" ] || [ -n "$SXMO_STYLUS_ID" ]; then
	sxmo_daemons.sh stop lisgd
fi

sxmo_hooks.sh statusbar locked

wait "$LEDPID"

case "$SXMO_WM" in
	dwm)
		# dmenu will grab input focus (i.e. power button) so kill it before going to
		# screenoff unless proximity lock is running (i.e. there's a phone call).
		sxmo_daemons.sh running proximity_lock -q || sxmo_dmenu.sh close
		;;
esac

# Start a periodic daemon (8s) "try to go to crust" after 8 seconds
# Start a periodic daemon (2s) blink after 5 seconds
# Resume tasks stop daemons
if [ -z "$SXMO_DISABLE_LEDS" ]; then
	sxmo_daemons.sh start idle_locker sxmo_idle.sh -w \
		timeout 8 'MUTEX_NAME=can_suspend sxmo_daemons.sh start going_deeper sh -c "sxmo_hooks.sh check_state_mutexes && exec sxmo_mutex.sh holdexec sxmo_screenlock.sh crust"' \
		resume 'sxmo_daemons.sh stop going_deeper' \
		timeout 5 'sxmo_daemons.sh start periodic_blink sxmo_run_periodically.sh 2 sxmo_led.sh blink red blue' \
		resume 'sxmo_daemons.sh stop periodic_blink' \
		timeout 12 'sxmo_daemons.sh start periodic_state_mutex_check sxmo_run_periodically.sh 10 sxmo_hooks.sh check_state_mutexes' \
		resume 'sxmo_daemons.sh stop periodic_state_mutex_check'
else
	sxmo_daemons.sh start idle_locker sxmo_idle.sh -w \
		timeout 8 'MUTEX_NAME=can_suspend sxmo_daemons.sh start going_deeper sh -c "sxmo_hooks.sh check_state_mutexes && exec sxmo_mutex.sh holdexec sxmo_screenlock.sh crust"' \
		resume 'sxmo_daemons.sh stop going_deeper' \
		timeout 12 'sxmo_daemons.sh start periodic_state_mutex_check sxmo_run_periodically.sh 10 sxmo_hooks.sh check_state_mutexes' \
		resume 'sxmo_daemons.sh stop periodic_state_mutex_check'
fi
