#!/bin/sh

# include common definitions
# shellcheck source=scripts/core/sxmo_common.sh
. "$(which sxmo_common.sh)"

#Make dbus session available
echo "$DBUS_SESSION_BUS_ADDRESS" > "$CACHEDIR"/dbus.bus

# in case of weird crash
echo "unlock" > "$LASTSTATE"
[ -f "$UNSUSPENDREASONFILE" ] && rm -f "$UNSUSPENDREASONFILE"

# Force audio over the main speaker
# and set a sane default volume
sxmo_audioout.sh Speaker
amixer sset 'Line Out Source' 'Mono Differential','Mono Differential'
amixer set "Line Out" 75%

# Play a funky startup tune if you want (disabled by default)
#mpv --quiet --no-video ~/welcome.ogg &

# Start the desktop widget (e.g. clock)
sxmo_hooks.sh desktop_widget &

# Enable automatic screen off and crust when phone is locked and idle
sxmo_lock_idle.sh &

if [ -f "$MMS_BASE_DIR/mms" ]; then
	mmsdtng &
fi

if [ -f "$VVM_BASE_DIR/vvm" ]; then
	vvmd &
fi

case "$SXMO_WM" in
	sway)
		useable_width="$(swaymsg -t get_outputs -r | jq '.[] | select(.focused == true) | .rect.width')"
		wob_sock="$XDG_RUNTIME_DIR"/sxmo.wobsock
		mkfifo "$wob_sock"
		tail -f "$wob_sock" 2> /dev/null | \
			wob -W "$((useable_width - 60))" -a top -a left -a right -M 10 &
		;;
esac
