#!/bin/sh

# include common definitions
# shellcheck source=scripts/core/sxmo_common.sh
. "$(which sxmo_common.sh)"

# in case of weird crash
echo "unlock" > "$SXMO_LASTSTATE"
[ -f "$SXMO_UNSUSPENDREASONFILE" ] && rm -f "$SXMO_UNSUSPENDREASONFILE"

# Force audio over the main speaker
# and set a sane default volume
sxmo_audioout.sh Speaker
amixer sset 'Line Out Source' 'Mono Differential','Mono Differential'
amixer set "Line Out" 75%

# Play a funky startup tune if you want (disabled by default)
#mpv --quiet --no-video ~/welcome.ogg &

case "$SXMO_WM" in
	sway)
		sxmo_daemons.sh start desktop_notifier mako
		sxmo_daemons.sh start wob sxmo_wob.sh
		sxmo_daemons.sh start menu_mode_toggler sxmo_menumode_toggler.sh
		;;
	dwm)
		sxmo_daemons.sh start desktop_notifier dunst

		# Auto hide cursor with touchscreen, Show it with a mouse
		if command -v "unclutter-xfixes" > /dev/null; then
			set -- unclutter-xfixes
		else
			set -- unclutter
		fi
		sxmo_daemons.sh start unclutter_xfixes "$1" --hide-on-touch --start-hidden

		# Set a pretty wallpaper
		feh --bg-fill /usr/share/sxmo/background.jpg

		sxmo_daemons.sh start autocutsel_1 autocutsel
		sxmo_daemons.sh start autocutsel_2 autocutsel -selection PRIMARY
		sxmo_daemons.sh start statusbar_xsetroot sxmo_status_xsetroot.sh
		;;
esac

if [ -f "${SXMO_MMS_BASE_DIR:-"$HOME"/.mms/modemmanager}/mms" ]; then
	sxmo_daemons.sh start mmsd mmsdtng "$SXMO_MMSD_ARGS"
fi

if [ -f "${SXMO_VVM_BASE_DIR:-"$HOME"/.vvm/modemmanager}/vvm" ]; then
	sxmo_daemons.sh start vvmd vvmd "$SXMO_VVMD_ARGS"
fi

# Start the desktop widget (e.g. clock)
sxmo_daemons.sh start desktop_widget sxmo_hooks.sh desktop_widget

# Periodically update some status bar components
sxmo_daemons.sh start statusbar_periodics sxmo_hooks.sh statusbar_periodics

# It watch network changes and update the status bar icon by example
sxmo_daemons.sh start network_monitor sxmo_networkmonitor.sh

# The daemon that display notifications popup messages
sxmo_daemons.sh start notification_monitor sxmo_notificationmonitor.sh

# To setup initial lock state
sxmo_screenlock.sh unlock

# turn on modemmonitor on login
# Note: if the modemmonitor is not on you can
# not receive texts/calls!
# (This can take up to 60 seconds)
sxmo_modemmonitortoggle.sh restart
