#!/usr/bin/env sh

# include common definitions
# shellcheck source=scripts/core/sxmo_common.sh
. "$(which sxmo_common.sh)"

echo "$DBUS_SESSION_BUS_ADDRESS" > "$CACHEDIR"/dbus.bus

# Force audio over the main speaker
# and set a sane default volume

sxmo_audioout.sh Speaker
amixer sset 'Line Out Source' 'Mono Differential','Mono Differential'
amixer set "Line Out" 75%

# Play a funky startup tune if you want (disabled by default)
#mpv --quiet --no-video ~/welcome.ogg &

sxmo_lock_idle.sh &

if [ -f "$HOME"/.mms/modemmanager/mms ]; then
	mmsdtng --nodaemon &
fi
