#!/bin/sh

sxmo_hooks.sh statusbar all

while : ; do
	sleep 55 & wait
	sxmo_hooks.sh statusbar periodics
done &
STATUSTIMEPID=$!

udev_tmp="$(mktemp)"
udevadm monitor -u -s power_supply >> "$udev_tmp" &
UDEVPID=$!
tail -f "$udev_tmp" | while read -r; do
	sxmo_hooks.sh statusbar battery
done &
STATUSBATTERYPID=$!

finish() {
	kill "$STATUSTIMEPID"
	kill "$STATUSBATTERYPID"
	kill "$UDEVPID"
	rm "$udev_tmp"
}
trap 'finish' TERM INT EXIT

wait "$STATUSTIMEPID"
wait "$STATUSBATTERYPID"
