#!/bin/sh

# we disable shellcheck SC2154 (unreferenced variable used)
# shellcheck disable=SC2154

# include common definitions
# shellcheck source=scripts/core/sxmo_common.sh
. "$(which sxmo_common.sh)"

set_time() {
	date +%H:%M | head -c -1 | sxmo_status.sh add 99-time
}

set_call_duration() {
	if ! pgrep sxmo_modemcall.sh > /dev/null; then
		sxmo_status.sh del 0-call-duration
		return
	fi

	NOWS="$(date +"%s")"
	CALLSTARTS="$(date +"%s" -d "$(
		grep -aE 'call_start|call_pickup' "$XDG_DATA_HOME"/sxmo/modem/modemlog.tsv |
		tail -n1 |
		cut -f1
	)")"
	CALLSECONDS="$(printf "%s - %s" "$NOWS" "$CALLSTARTS" | bc)"
	printf "%ss " "$CALLSECONDS" | sxmo_status.sh add 0-call-duration
}

_modem() {
	MMCLI="$(mmcli -m any -J)"
	MODEMSTATUS=""

	if [ -z "$MMCLI" ]; then
		printf "%s" "$icon_cls"
	else
		MODEMSTATUS="$(printf %s "$MMCLI" | jq -r .modem.generic.state)"
		case "$MODEMSTATUS" in
			locked)
				printf "%s" "$icon_lck"
				;;
			registered|connected)
				MODEMSIGNAL="$(printf %s "$MMCLI" | jq -r '.modem.generic."signal-quality".value')"
				if [ "$MODEMSIGNAL" -lt 20 ]; then
					printf ""
				elif [ "$MODEMSIGNAL" -lt 40 ]; then
					printf ""
				elif [ "$MODEMSIGNAL" -lt 60 ]; then
					printf ""
				elif [ "$MODEMSIGNAL" -lt 80 ]; then
					printf ""
				else
					printf ""
				fi
				;;
			enabled)
				printf "%s" "$icon_ena"
				;;
			connecting|searching)
				printf "%s" "$icon_dot"
				;;
		esac
	fi

	if [ "$MODEMSTATUS" = "connected" ]; then
		printf " "
		USEDTECHS="$(printf %s "$MMCLI" | jq -r '.modem.generic."access-technologies"[]')"
		case "$USEDTECHS" in
			*5gnr*)
				printf 5g # no icon yet
				;;
			*lte*)
				printf 4g # ﰒ is in the bad range
				;;
			*umts*|*hsdpa*|*hsupa*|*hspa*|*1xrtt*|*evdo0*|*evdoa*|*evdob*)
				printf 3g # ﰑ is in the bad range
				;;
			*edge*)
				printf E
				;;
			*pots*|*gsm*|*gprs*)
				printf 2g # ﰐ is in the bad range
				;;
		esac
	fi
}

set_modem() {
	_modem | sxmo_status.sh add 10-modem-status
}

set_modem_monitor() {
	if pgrep -f sxmo_modemmonitor.sh > /dev/null; then
		sxmo_status.sh add 20-modem-monitor-status "$icon_mod"
	else
		sxmo_status.sh del 20-modem-monitor-status
	fi
}

set_wifi() {
	WLANSTATE="$(tr -d "\n" < /sys/class/net/wlan0/operstate)"
	if [ "$WLANSTATE" = "up" ]; then
		sxmo_status.sh add 30-wifi-status "$icon_wif"
	else
		sxmo_status.sh del 30-wifi-status
	fi
}

set_vpn() {
	VPNDEVICE="$(nmcli con show | grep vpn | awk '{ print $4 }')"
	WGDEVICE="$(nmcli con show | grep wireguard | awk '{ print $4 }')"
	if [ -n "$VPNDEVICE" ] && [ "$VPNDEVICE" != "--" ]; then
		sxmo_status.sh add 30-vpn-status "$icon_key"
	elif [ -n "$WGDEVICE" ] && [ "$WGDEVICE" != "--" ]; then
		sxmo_status.sh add 30-vpn-status "$icon_key"
	else
		sxmo_status.sh del 30-vpn-status
	fi
}

_battery() {
	for power_supply in /sys/class/power_supply/*; do
		if [ "$(cat "$power_supply"/type)" = "Battery" ]; then
			PCT="$(cat "$power_supply"/capacity)"
			BATSTATUS="$(cut -c1 "$power_supply"/status)"
		fi
	done

	if [ "$BATSTATUS" = "C" ]; then
		if [ "$PCT" -lt 20 ]; then
			printf ""
		elif [ "$PCT" -lt 30 ]; then
			printf ""
		elif [ "$PCT" -lt 40 ]; then
			printf ""
		elif [ "$PCT" -lt 60 ]; then
			printf ""
		elif [ "$PCT" -lt 80 ]; then
			printf ""
		elif [ "$PCT" -lt 90 ]; then
			printf ""
		else
			printf ""
		fi
	else
		if [ "$PCT" -lt 10 ]; then
			printf ""
		elif [ "$PCT" -lt 20 ]; then
			printf ""
		elif [ "$PCT" -lt 30 ]; then
			printf ""
		elif [ "$PCT" -lt 40 ]; then
			printf ""
		elif [ "$PCT" -lt 50 ]; then
			printf ""
		elif [ "$PCT" -lt 60 ]; then
			printf ""
		elif [ "$PCT" -lt 70 ]; then
			printf ""
		elif [ "$PCT" -lt 80 ]; then
			printf ""
		elif [ "$PCT" -lt 90 ]; then
			printf ""
		else
			printf ""
		fi
	fi

	[ -z "$SXMO_BAR_HIDE_BAT_PER" ] && printf " %s%%" "$PCT"
}

set_battery() {
	 _battery | sxmo_status.sh add 40-battery-status
}

_volume() {
	AUDIODEV="$(sxmo_audiocurrentdevice.sh 2>/dev/null)"
	AUDIOSYMBOL="$(printf %s "$AUDIODEV" | cut -c1)"
	if [ "$AUDIOSYMBOL" = "L" ] || [ "$AUDIOSYMBOL" = "N" ] || [ "$AUDIOSYMBOL" = "M" ]; then
		printf "" #pipewire or speakers or none, use no special symbol
	elif [ "$AUDIOSYMBOL" = "H" ]; then
		printf "%s " "$icon_hdp"
	elif [ "$AUDIOSYMBOL" = "E" ]; then
		printf "%s " "$icon_ear" #earpiece
	fi
	VOL=0
	[ "$AUDIODEV" = "None" ] || VOL="$(
		amixer sget "$AUDIODEV" |
		grep -oE '([0-9]+)%' |
		tr -d ' %' |
		awk '{ s += $1; c++ } END { print s/c }'  |
		xargs printf %.0f
	)"
	if [ "$AUDIODEV" != "None" ]; then
		if [ "$VOL" -gt 66 ]; then
			printf "%s" "$icon_spk"
		elif [ "$VOL" -gt 33 ]; then
			printf "%s" "$icon_spm"
		elif [ "$VOL" -gt 0 ]; then
			printf "%s" "$icon_spl"
		elif [ "$VOL" -eq 0 ]; then
			printf "%s" "$icon_mut"
		fi
	fi
}

set_volume() {
	 _volume | sxmo_status.sh add 50-volume
}

case "$1" in
	time|call_duration|modem|modem_monitor|wifi|vpn|battery|volume)
		set_"$1"
		;;
	periodics|state_change) # 55 s loop and screenlock triggers
		set_time
		set_modem
		set_battery
		;;
	all)
		sxmo_status.sh reset
		set_time
		set_call_duration
		set_modem
		set_modem_monitor
		set_wifi
		set_vpn
		set_battery
		set_volume
		;;
	*)
		exit # swallow it !
		;;
esac

