#!/bin/sh

# This hook is called when the system becomes unlocked again

sxmo_daemons.sh start idle_locker sxmo_idle.sh -w \
	timeout 120 'sxmo_daemons.sh start periodic_deeper sxmo_run_periodically.sh 10 sxmo_screenlock_deeper.sh --idle' \
	resume 'sxmo_daemons.sh stop periodic_deeper'
