#!/bin/sh
# configversion: 1

# This hook is called when the system becomes unlocked again

sxmo_led.sh blink red green &
LEDPID=$!

sxmo_wm.sh dpms off
sxmo_wm.sh inputevent touchscreen on
[ -z "$SXMO_STYLUS_ID" ] || sxmo_wm.sh inputevent stylus on
sxmo_hooks.sh lisgdstart

sxmo_hooks.sh statusbar state_change
sxmo_hooks.sh statusbar locked

wait "$LEDPID"

NETWORKRTCSCAN="/sys/module/8723cs/parameters/rtw_scan_interval_thr"
echo 16000 > "$NETWORKRTCSCAN"

# Start a periodic daemon (10s) "try to go to lock" after 120 seconds
# Resume tasks stop daemons
sxmo_daemons.sh start idle_locker sxmo_idle.sh -w \
	timeout "${SXMO_UNLOCK_IDLE_TIME:-120}" 'sxmo_daemons.sh start periodic_deeper sxmo_run_periodically.sh 10 sxmo_screenlock_deeper.sh --idle' \
	resume 'sxmo_daemons.sh stop periodic_deeper'

sxmo_daemons.sh signal desktop_widget -12
