#!/usr/bin/env sh

# This script is executed after you received a text
#You can use it to play a notification sound or forward the sms elsewhere

#The following parameters are provided:
#$1 = Sender Number
#$2 = VVM Unique Id

mpv --quiet --no-video /usr/share/sxmo/notify.ogg
