export SXMO_DISABLE_LEDS=1
export SXMO_STATUS_DATE_FORMAT="%Y-%m-%d %H:%M"
export SXMO_DISABLE_KEYBINDS=1
export SXMO_STATES="unlock locker"
export SXMO_UNLOCK_IDLE_TIME=300
export SXMO_NO_MODEM=1
export SXMO_NO_KEYBOARD=1
