#!/usr/bin/env sh

# Please modify this file to your liking

# Important Instructions:
#  All processes you launch from this script must
#  be non-blocking: launch them in the background (using &)
#  or ensure they return quickly. Only after this script
#  finishes will the window manager be loaded

# Set a pretty wallpaper
feh --bg-fill /usr/share/sxmo/background.jpg

# Show conky (the clock)
conky -c /usr/share/sxmo/appcfg/conky.conf -d #12 hour clock (am/pm)
#conky -c /usr/share/sxmo/appcfg/conky24h.conf -d  #24 hour clock

# Run actions on start
# By default, setup audio over the main speaker
# and set a sane default volume
sxmo_hooks.sh wm_start

# You will sometime get SMS or calls from not
#  country code prefixed phone numbers. To make
#  it easy to fixup configure the default countryu.
#export DEFAULT_COUNTRY=FR

# turn on modemmonitor on login
# Note: if the modemmonitor is not on you can
# not receive texts/calls!
# (there is a bit of a delay to
# give the modem some time to set up)
sxmo_modemmonitortoggle.sh restart &


### Configuration Parameters ###

# Note that this is just a subset of all available
# parameters, see the sxmo documentation for more.

# Use firefox as default browser if installed
command -v firefox && export BROWSER=firefox

# Prepopulate Subreddits menu with custom subreddits
#export SXMO_SUBREDDITS="postmarketos pinephoneOfficial pinephone unixporn"

# Change the default terminal command
# export TERMCMD="st -e"

# Immediately turn the screen off when locking the device
# (e.g. disables blue led / screen on lock mode all together)
#export SXMO_LOCK_SCREEN_OFF=1

# Immediately suspend the phone when locking
#export SXMO_LOCK_SUSPEND=1

# When scrolling past the beginning or end of a menu, wrap it around:
#export DMENU_WRAP_AROUND=1

# Enable audio feedback on keypress
#export KEYBOARD_ARGS="-o | clickclack -f /usr/share/sxmo/keypress.wav"

# Or, enable vibration feedback on keypress
#export KEYBOARD_ARGS="-o | clickclack -V"

# Auto hide cursor with touchscreen, Show it with a mouse
unclutter-xfixes --hide-on-touch --start-hidden &
